# configuration chess game server
step_time_left: 30  # seconds
reserve_time_left: 300  # seconds
addr: ":8081"
websocket_url: "/ws/chess"
original_client_url: "http://localhost:8080"
offer_draw_times_left: 3
time_left_for_confirm_draw: 10  # seconds
swap_teams_after_making_new_game: true
